### ISSUE TITLE
Values of SemanticExpressivity

### ISSUE THREAD

**Issue by joergwa** [ISE-FIZKarlsruhe/nfdico-ontology#18]
We would like to define SemanticExpressivity as a closed class with predifined values. What are the values? Please provide a list.

**Comment by lysander07** [comment]
I suggest to go for the following terms (if this granularity is suitable for you):

1. Glossary (list of terms, aka terminology, with natural language definitions)
2. Controlled Vocabulary (like glossary, only that there is a dedicated curation mechanism for new terms)
3. Thesaurus (terminology, relations between the terms, as e.g. broader/narrower)
4. Taxonomy (class hierarchy, can be strict or non strict, can contain instances)
5. Ontology
(6. Rules or FOL)

Within Ontology, we can distinguish the expressivity by designating the respective logic or fragment of logic we are referring to, as e.g. PL,ALC,SHROIC,  ...

In theory, there are logics more complex (and more expressive) than FOL. I don't think that we will need them by now
