### ISSUE TITLE
[discussion] Adjust term nfdico:Contributor

### ISSUE THREAD

**Issue by joergwa** [ISE-FIZKarlsruhe/nfdico-ontology#4]
- `nfdico:Contributor` defined as: An organisation that contributes to the creation of data.
- A contributor could also be a person
- Also contributes to resources e.g. software, standards, etc, not only creation of data

**Comment by ebrahimnorouzi** [comment]
They deleted this class in nfdico 1.1.

**Comment by joergwa** [comment]
OK, there is a property now.
